have_GPU : Flase
port_number : 5000

huggingface_model_name : "./models/fusecap/"

ocr_language : 'ch'

result_json_keys:
  image_id_key : "imageId"
  image_caption : "imageCaption"
  image_caption_tokens_key : "imageCaptionTokens"
  image_ocr_text_key : "imageOcrText"
