have_GPU : Flase

huggingface_model_name : "./models/fusecap/"

ocr_language : 'ch'
# translator_src_language : 'zh-CN'
# translator_des_language : 'en'

result_json_keys:
  image_id_key : "imageId"
  image_caption : "imageCaption"
  image_caption_tokens_key : "imageCaptionTokens"
  image_ocr_text_key : "imageOcrText"
